### ISSUE TITLE
Potential row limit on server

### ISSUE THREAD

**Issue by youanden** [sbruno81/rets-client#10]
I'm trying to execute a line like so:
```
client.queryWithOpts('Property', '1', '(246=A),(61=|BROWARD,DADE)', {limit: 10, offset: 0}, function(error, data) {
	fs.writeFile("./test.txt", JSON.stringify(data))
	console.log(error);
});
```

The `data.length` is always 5000 when I have no limit or 10000 as my limit. Offset does not work on my RETS endpoint and returns an error like so:
```
{ [Error: RETS Server returned an error - ReplyCode: 20203 ReplyText: Offset is not supported.  Reference ID: 7be5d629-085a-4cba-a6e0-769b50b8ee78]
  replyCode: '20203',
  replyText: 'Offset is not supported.  Reference ID: 7be5d629-085a-4cba-a6e0-769b50b8ee78' }
```

Do you think this problem is related with the server? Is there something I can do to confirm this from my side? There is no publicly available documentation on my RETS feed website.

**Comment by sbruno81** [comment]
Hi Georgiy,

I've experienced the same issue with the rets server I develop against.
Even though I set a limit on some queries to a value greater than 5000 I
only get back 5000. I've seen this happen on a java rets client
implementation and also when hitting the rets server directly. My sense is
that this is a problem related with the server. Is there a technical point
of contact that maintains your rets server that you can get in touch with?

-Steve

**Comment by youanden** [comment]
Thanks for the quick reply,

Yes, we have a point of contact that may be able to answer that for us. I'll go ahead and ask.

**Comment by youanden** [comment]
Got a response back from my point of contact:
> Yes the 5000 is a limit by a company business decision. Once the the download is completed the first time all updates will be in one pull if done daily.

**Comment by scottconrad** [comment]
some RETS providers will give you up to 25 tries to download the full set of data, then it is incrementally after that. Sometimes they only let you go back 14 days, others will have this limit like you mentioned.  I'm working with one right now where they only allow 100 per search, and there are around 130,000 records to download.

**Comment by zacronos** [comment]
@scottconrad, thanks for the additional input.  For anyone else who finds this ticket, this sort of business rule will have to be dealt with using the `offset` option to iteratively request additional records.

Closing the ticket since this is a server-side setting, not client-side.
