### ISSUE TITLE
Documentation on lookup metadata & values

### ISSUE THREAD

**Issue by invisibled** [sbruno81/rets-client#104]
I'd love to have a bit more documentation on how to retrieve metadata lookup values. Is there a way to retrieve just one field's values? Something like `client.metadata.getLookupTypes("Property ","Area")`.

I'm currently looking through the source code trying to figure out if and how i can do this. Any info would be welcomed! thank you.

**Comment by esvinson** [comment]
You would need to know the LookupName for the field which you get by pulling the table schema.

Table schema:
```js
    return client.metadata.getTable(feedResource.resource, feedResource.class)
      .then((results) => get(results, 'results[0].metadata', []))
```

Lookup values once you know the LookupName:
```js
return client.metadata.getLookupTypes(feedResource.resource, lookupName)
    .then((lookupTypes) => get(lookupTypes, 'results[0].metadata', []));
```

**Comment by invisibled** [comment]
ahh easy, thank you!
