### ISSUE TITLE
GetObject doesn't use host provided by login response

### ISSUE THREAD

**Issue by mlucic** [sbruno81/rets-client#105]
I've compared the result of logging in and running getAllObjects for two different MLS'. The GetObject value for the first MLS is simply the servers getObject endpoint, however for the second MLS they provide the host plus the path. When I log the URI object being used for the requests I notice that the host is not the one that was provided in the login response under GetObject, but simply the same host for the rets server. As a result, the client always returns 404 since it is requesting data from the incorrect host.

**Comment by esvinson** [comment]
Very interesting, which MLS is the one that's providing the full URI?

**Comment by esvinson** [comment]
I do see the issue in the normalizeUrl function, https://github.com/sbruno81/rets-client/blob/master/lib/utils/normalizeUrl.coffee#L9-L20 function.

**Comment by esvinson** [comment]
@mlucic can you try manually making the change in #106 and see if that fixes your issue and doesn't cause any authentication issues?

**Comment by mlucic** [comment]
@esvinson Unfortunately that just results in a 401 on login. "RetsServerError: RETS Server error while attempting login - HTTP Status 401 returned (Unauthorized)"

**Comment by esvinson** [comment]
I was worried about that, what MLS is that?

**Comment by mlucic** [comment]
@esvinson IRES https://ires-net.com/

**Comment by mlucic** [comment]
IRES http://www.ires-net.com/

**Comment by esvinson** [comment]
Looks like they're going to possibly merge with REColorado at some point which I know works, but we don't have credentials for IRES so it's not going to be something I can easily test/debug at this time.

**Comment by mlucic** [comment]
@esvinson Not sure what changed from the last time I tested #106 but I just tested again and I successfully got photos.

**Comment by esvinson** [comment]
@mlucic did you maybe not run the build process after making the change previously?  If it's working I can reopen the pull request.

**Comment by mlucic** [comment]
@esvinson Whatever happened doesn't seem to be the case anymore. With the changes in 106 I'm able to get IRES photos successfully. I would recommend reopening.

**Comment by esvinson** [comment]
Reopened.
