### ISSUE TITLE
RETS Server error while attempting search - HTTP Status 401 returned (Access Denied)

### ISSUE THREAD

**Issue by mlucic** [sbruno81/rets-client#108]
The change in #106 has unfortunately resulted in a 401 error being thrown when attempting a search on DABR's (Dayton Area Board of Realtors) RETS server. Reverting the changes from #106 fixes the issue, however that would not be a viable solution as it would reintroduce #105 .

**Comment by esvinson** [comment]
Bah, another one I don't have access to! :-P

Try making sure you're hitting the proper URL and not one that's redirecting to a 301/302 or something.

Try turning on debug `DEBUG=rets-client:*` in environment.
Then check the output for the `body` after the login command runs.
It should show a list of endpoint URLs.  You should be logging into the URL specified by the `Login=` endpoint, or is it returning a list of relative URLs?

**Comment by mlucic** [comment]
@esvinson FYI the issue isn't when logging in, the client logs in without error. The issue occurs when executing a search.

**Comment by esvinson** [comment]
I understand that, but if it's logging in to a different URL than what it expects the cookies are stored for the domain you logged into, not the one it might be trying to query.

**Comment by mlucic** [comment]
@esvinson Looking at the login response, we can see the source of the issue. The URLs in the response are all absolute. We login using a proxy (RETS server has IP restrictions...), but when we attempt to execute a search it uses the absolute URL from the login response, hence the 401. A potential solution would be to allow for proxy settings to be defined on the client such that hosts can be mapped to corresponding proxies.

**Comment by esvinson** [comment]
Try passing {useTunnel: true} as an option to the RETS client if your proxy supports it.

**Comment by mlucic** [comment]
@esvinson Simply setting proxyUrl did the trick for us. Appreciate the assistance in clearing things up.
