### ISSUE TITLE
Using rets-client with AWS Lambda

### ISSUE THREAD

**Issue by steltz** [sbruno81/rets-client#114]
Is anyone using this package with AWS Lambda?

I can run my Lambda function locally using the Serverless framework and everything works fine. But when I upload my function to Lambda, I'm getting an error with one of the dependencies of this package. I'm getting the following error with the `node-expat` package:

```
{
  "errorMessage": "/var/task/node_modules/node-expat/build/Release/node_expat.node: invalid ELF header",
  "errorType": "Error",
  "stackTrace": [
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "bindings (/var/task/node_modules/bindings/bindings.js:81:44)",
    "Object.<anonymous> (/var/task/node_modules/node-expat/lib/node-expat.js:4:32)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/node_modules/rets-client/dist/utils/retsHttp.js:16:11)"
  ]
}
```

```
START RequestId: 114c9174-9128-11e8-9808-a96e749a880c Version: $LATEST
module initialization error: Error
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/var/task/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/var/task/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/rets-client/dist/utils/retsHttp.js:16:11)
END RequestId: 114c9174-9128-11e8-9808-a96e749a880c
REPORT RequestId: 114c9174-9128-11e8-9808-a96e749a880c	Duration: 35.18 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 37 MB	
module initialization error
Error
```

I found this post about an unrelated package which seems to be the same issue I'm having:

https://stackoverflow.com/questions/47891144/aws-lambda-module-initialization-error-error-when-running-camaro-serverless

**Comment by steltz** [comment]
I found this closed issue on the node-expat repo:

https://github.com/astro/node-expat/issues/173

`node-expat` seems to be an old, unmaintained package. I wonder what the effort would be to refactor this package out of the dependencies and replace with a newer XML parser.

**Comment by barrct** [comment]
You need to ensure that you build the package in the Lambda environment.I forget exactly what it is, but it is AWS Linux.So, fire up an AWS linux EC2, pull your source down, NPM install and let it build there.That is what needs zipped up and pushed into Lambda. Because of that, I store the npm data within my git repo so that I maintain the source compiled module.
If needed, I can pull out some of my notes, but mine has been working perfectly for over a year now with zero issues.
Chris.

    On Thursday, July 26, 2018, 7:32:15 PM EDT, Nicholas Stelter <notifications@github.com> wrote:  
 
 
I found this closed issue on the node-expat repo:

astro/node-expat#173

node-expat seems to be an old, unmaintained package. I wonder what the effort would be to refactor this package out of the dependencies and replace with a newer XML parser.

**Comment by steltz** [comment]
@barrct Thanks for the response! I've been having a really tough time getting the `rets-client` package to run in Lambda.

I spun up an ec2 instance using the Linux AMI that Lambda uses:

`amzn-ami-hvm-2017.03.1.20170812-x86_64-gp2`

On my ec2 instance, I can't get node-expat to install properly. I've tried running `npm i` using all the versions of Node supported by Lambda (v4.3, v6.10, v8.10).

Do you have any other tips for me?

**Comment by michaelrizzello** [comment]
@steltz have you been able to get rets-client to work on lambda?

**Comment by irkanu** [comment]
@steltz Would love to know what you did to resolve this.
