### ISSUE TITLE
cannot get agent by id: client.search.query('Agent', 'Agent', "(AgentID=CORC-6)")

### ISSUE THREAD

**Issue by fullstackrelibit** [sbruno81/rets-client#121]
I want to get Agent records by using client.search.query('Agent', 'Agent', "(AgentID=CORC-6)") query.

But it is giving empty records:
"data": {
    "results": [],
    "maxRowsExceeded": false,
    "replyCode": "0",
    "replyTag": "OPERATION_SUCCESSFUL",
    "replyText": "Operation Successful",
    "count": 0,
    "rowsReceived": 0
  }

I tried everything and using 5.2.3 version.

**Comment by esvinson** [comment]
For any values with non-alphanumeric characters it's usually a good idea to quote the value.

Try:
`client.search.query('Agent', 'Agent', '(AgentID="CORC-6")')` 

If that still doesn't find anything that ID might be invalid or your credentials may not have access to it.

**Comment by fullstackrelibit** [comment]
Thank's this is working now.
