### ISSUE TITLE
Streaming example always rejecting

### ISSUE THREAD

**Issue by geoffmc** [sbruno81/rets-client#24]
In the streaming example do you maybe have the (reject, resolve) mixed up in the promise? When I run the example code it is always rejecting at the end when it hits the "done" event. If I swap them to be (resolve, reject) then it seems to work perfectly.

Under the heading "Simple streaming example" this is the line:
return new Promise(function **(reject, resolve)** {

**Comment by zacronos** [comment]
Indeed I do.  I'll fix it.  Thanks!
