### ISSUE TITLE
Property Stream Example

### ISSUE THREAD

**Issue by lance0821** [sbruno81/rets-client#25]
When trying to run the property streaming example code, the function seems to execute, but I don't see any evidence of returned results? Is this the expected behavior?

**Comment by zacronos** [comment]
What are you doing for `doAsyncProcessing()`?

I've changed the example now to provide a sample `doAsyncProcessing()` function that displays the results -- and importantly, which demonstrates how you have to call the `callback`.  Does that help?

**Comment by lance0821** [comment]
Thanks I'll check it out when I get home and let you know.

**Comment by lance0821** [comment]
Yes that helped a lot thanks again
