### ISSUE TITLE
Overcome server limit

### ISSUE THREAD

**Issue by lance0821** [sbruno81/rets-client#26]
If there a built in option to , pull the results in chunks and overcome the RETS server limit?

**Comment by zacronos** [comment]
I'll leave this ticket open in case someone wants to implement it and contribute a PR, but honestly I expect that such a feature would be more complicated than it sounds to implement.

**Comment by lance0821** [comment]
Could a count parameter of 2 be used in client settings, then a loop based on an offset?

**Comment by zacronos** [comment]
Using `count: 2` will work most of the time, but there is no guarantee there won't be changes to the result list while you are looping.  The safest way to do it is to check the `maxRowsExceeded` flag on every result, and continue to query using offset whenever that is `true` -- but even that isn't guaranteed to work.  Depending on your search query, on rare occasion you could see a listing twice in the course of looping, or a valid result might never be seen during looping.  The RETS standard doesn't provide a reliable method to paginate results.

Something like this (either using `count: 2`, or checking `maxRowsExceeded`) could work (with the caveat above) for the non-streaming part of the API without any trouble, as long as the total result wasn't so big it caused memory issues to load it all into memory at once.  It gets more complicated to implement this for the streaming part of the API.

Note that this can be done outside rets-client already, just not as a built-in option.  You can pass `count: 2` in the options parameter of `client.search.query`.  See the README example where `limit:100, offset:10` are set -- the `count` option is also supported there.
