### ISSUE TITLE
Not doing anything with 'set-cookie' header??

### ISSUE THREAD

**Issue by luncht1me** [sbruno81/rets-client#28]
I'm trying to use this to connect to RETS, I have a user/pass UA and UApass, authorized by a local board.

On first login, I get a 401 Unauthorized which contains the header 'set-cookie:', but as far as I can tell, this client doesn't do anything with this header? The RETS 1.7 docs say this is a challenge which then needs to recalc UA-Auth w/ so I've tried manually setting this incoming ID as my sessionID then trying to login again, but then I recieve a `<RETS ReplyCode="20037" ReplyText="RETS-UA-Authorization failed." />`. 

I again can only assume it's because there's no Cookie handling in the headers for this client. I've searched the code and find nothing about Cookies, despite 'tough-cookie' being required as a dependency.  How are any of you connecting if this is the standard??

**Comment by zacronos** [comment]
Basic cookie handling happens implicitly through the "jar" functionality of the `request` dependency.  It sounds like some special handling is needed though.

As for how the rest of us are successfully connecting, keep in mind that one (IMO frustrating) things about RETS is that it gives servers a lot of flexibility in terms of behavior.  I haven't checked but I would assume the standard doesn't _require_ that a challenge be sent.  (There are lots of things in the standard that can _possibly_ happen, but which _don't_ happen on most servers -- and that's not even counting the fact that not all servers are using RETS 1.7!)  Since this library is based on donated time, support for the various possibilities happens as people need it, not all at once, and so far no one has needed this.

I'll take a look at the standard and add support for the challenge when I can, but unfortunately I can't give you a timeline right now, as I am much more busy than usual.  I would welcome a PR if you or anyone else is able to get it working.

**Comment by luncht1me** [comment]
Thanks for getting back to me, I'm actively trying to get this to work, so when I do successfully get things happening I'll let you know what I had to do for this kind of login transaction.

**Comment by luncht1me** [comment]
Alright, it's a new issue. I'm not sure what happened but now my cookies are getting set when Set-Cookie is sent from the server as you described..

What's required for me specifically, which I'm currently working on, is that my 'RETS-UA-Authorization' header needs to be dynamic. I see you have already in `client.js` the propery UA-Authorization function which takes SessionID into consideration. Thing is - for me atleast - after the successful login, server response header contains  `Set-Cookie: 'RETS-Session-ID=-d3136de7-5fe2-40d1-9a2a-08dadac1a7d4-; path=/'`. Now, all my subsequent calls need `RETS-UA-Authourization` to be  recomputed with this new SessionID. 

How can we modify the client request headers once the client's been initalized with settings? I'm sure my problems would be solved if there was an option to change headers for the client at any point. Are the latest response headers attached to the `client` object at all? I'm only just digging into the code for this project.

**Comment by zacronos** [comment]
Gotcha.  There's no way to do that currently from outside rets-client.

If you're working on a PR, note that you'll need to make changes to the coffeescript code, as the javascript is transpiled from it.

From within rets-client, I think you'll want to save a reference to the "cookie jar" that is created for the client (see line 54 of client.coffee).  After login you can check the jar for the cookie you want, and if it is set then recalculate the auth header and overwrite `@headers['RETS-UA-Authorization']` -- I think that will impact all future requests.

**Comment by luncht1me** [comment]
Thanks for the input, I'll look into modifying the coffeescript at some point.

But, here's what I did to get this authorization scheme to work.

I defined two functions, one is taken directly from the client - the function that computes the User-Agent Auth Header, and another which detects the RETS-Session-ID cookie in the client headers, strips it out and sets it to the settings.sessionId property of the client then calls the computeUAHeader function to set new a RETS-UA-Authorization Digest for the rest of the calls.

```
// crypto function to reset RETS-UA-Authorization in a dynamic fashion.
function computeUAHeader(client) {
	var a1, retsUaAuth;
	if(!client.settings.sessionId){
		console.log("NO SESSIONID");
		return false
	} else {
	a1 = crypto.createHash('md5').update([client.settings.userAgent, client.settings.userAgentPassword].join(":")).digest('hex');
	retsUaAuth = crypto.createHash('md5').update([a1, "", client.settings.sessionId || "", client.settings.version || client.headers['RETS-Version']].join(":")).digest('hex');
	client.headers['RETS-UA-Authorization'] = "Digest " + retsUaAuth;
	console.log("New UA-Auth header set, result", client.headers['RETS-UA-Authorization']);
	return true
	}
}

// Function for handling new cookie for header changes, should be run after initial login
function checkSessionHeader(client) {
	console.log("sign-in successful, setting session?");
	var cookie = client.metadata.retsSession.head().headers.cookie;
	console.log("looking for cookie", cookie);
	if(cookie.indexOf('RETS-Session-ID') != -1) {
		var cookieSplit, retsIdx, retsCookie;
		console.log("RETS-Session-ID found!");
		cookieSplit = cookie.split(';');
		console.log("cookieSplit", cookieSplit);
		var cIdx = -1;
		_.forEach(cookieSplit, function (c, i) {
			if (c.indexOf('RETS-Session-ID')) {
				cIdx = i;
			}
		});
		console.log("cIdx", cIdx);
		if (cIdx != -1) {
			console.log("cIdx valid... continuing");
			retsCookie = cookieSplit[cIdx].split('=')[1];
			console.log("RETS-Session-ID is ", retsCookie,
				"... Setting client.settings.sessionId and recomputing UA-Authorization Header");
			client.settings.sessionId = retsCookie;
			// Compute new Header
			return computeUAHeader(client);
		}
	}
	else return false;
}
```

And then in the rets.getAutoLogoutClient my app flow goes as follows:

```
function tableClient() {
	rets.getAutoLogoutClient(clientSettings, function(client){
		console.log("===================================");
		console.log("========  System Metadata  ========");
		console.log("===================================");
		writeStream.write("\r\n  ***** SYSTEM META DATA ");
		outputFields(client.systemData);

		// Session needs to be set for all subsequent calls, so pull the cookie w/ the required data and recompute UA-HEADER
		// Once new UA-Header is computer, we can continue with the rest of the client calls.
		if (checkSessionHeader(client)){
				// Do rest of the client calls after
				return client.metadata.getResources()
					.then(function(data){
						dumpStream.write(JSON.stringify(data)+"\r\n\r\n");
						console.log("======================================");
						console.log("=============  Metadata  =============");
						console.log("======================================");
						writeStream.write("\r\n  ***** METADATA ");
						outputFields(data.results[0].info);
///... etc.
                } else {
			console.log("Error in checkSessionHeader, returned FALSE");
		}
```
