### ISSUE TITLE
Issue with query on RETS/1.7.2

### ISSUE THREAD

**Issue by josephbisaillon** [sbruno81/rets-client#32]
I'm trying to do a simple query but I keep getting an error thrown. 

`client.search.query("Property", "ALL", "(County=|10000005773)", {limit:25, offset:1})`

`ERROR: issue encountered: RetsReplyError: RETS Server replied with an error code - ReplyCode 20203 (MISC_SEARCH_ERROR); ReplyText: Illegal RestrictedIndicator character, values are a..z, A..Z, 0..9`

Just wondering if I am doing something wrong.

**Comment by josephbisaillon** [comment]
Oh and even if I remove the | in the query it still gives the same error.

**Comment by zacronos** [comment]
Huh, well that's weird.  The arbitrary restrictions MLSs choose to impose never cease to surprise me.

Try adding the option: `restrictedIndicator: 'RESTRICTED'` and see if that does it.  The default we use in this library is `***`, but apparently your MLS doesn't allow that.

**Comment by josephbisaillon** [comment]
That worked, thanks!
