### ISSUE TITLE
error: options.uri is a required argument

### ISSUE THREAD

**Issue by petercz1** [sbruno81/rets-client#36]
Hi Bruno,

I'm getting the above error with 4.2.0 - it's an error coming from request.js 2.72.0 line 244:

```
// A URI is needed by this point, emit error if we haven't been able to get one
  if (!self.uri) {
    return self.emit('error', new Error('options.uri is a required argument'))
  }
```

Here are my options:

```
var clientSettings = {
    loginUrl: 'http://xxx',
    username: 'xxx',
    password: 'xxx',
    version: 'RETS/1.7.2',
    userAgent: 'RETS node-client/4.x'
};
```

Am I doing something wrong? (again ....)

PC

**Comment by petercz1** [comment]
never mind.... MORE COFFEEE.....

**Comment by nshkuro** [comment]
Hi Peter,
I got the same error. Can you say how you solve this problem?

**Comment by petercz1** [comment]
Hi,

I can't remember (and I've just checked my code again to see if it jogs my memory!) but it was definitely a mistake on my part. I do remember solving it my knocking up a test rig and building out from that, and it was something simple.

PC
