### ISSUE TITLE
Error: options.uri is a required argument

### ISSUE THREAD

**Issue by nshkuro** [sbruno81/rets-client#38]
Hi guys,  thanks for your work!

I have some troubles. I always get the error after login call and all next request are broken.

> Unhandled rejection Error: options.uri is a required argument
>     at Request.init (/vagrant/node_modules/rets-client/node_modules/request/request.js:246:31)
>     at new Request (/vagrant/node_modules/rets-client/node_modules/request/request.js:142:8)
>     at request (/vagrant/node_modules/rets-client/node_modules/request/index.js:55:10)
>     at /vagrant/node_modules/rets-client/node_modules/request/index.js:102:12
>     at /vagrant/node_modules/rets-client/node_modules/request/index.js:102:12
>     at tryCatcher (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
>     at ret (eval at <anonymous> (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:14:23)
>     at /vagrant/node_modules/rets-client/dist/utils/retsHttp.js:25:14
>     at tryCatcher (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
>     at Function.Promise.attempt.Promise.try (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/method.js:31:24)
>     at Object.callRetsMethod (/vagrant/node_modules/rets-client/dist/utils/retsHttp.js:24:26)
>     at Object.logout (/vagrant/node_modules/rets-client/dist/utils/auth.js:80:21)
>     at Client.logout (/vagrant/node_modules/rets-client/dist/client.js:123:19)
>     at /vagrant/node_modules/rets-client/dist/client.js:138:25
>     at Object.finallyHandler (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/finally.js:39:23)
>     at Object.tryCatcher (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:507:31)
>     at Promise._settlePromiseAt (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:581:18)
>     at Promise._settlePromiseAtPostResolution (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:245:10)
>     at Async._drainQueue (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/async.js:128:12)
>     at Async._drainQueues (/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate](/vagrant/node_modules/rets-client/node_modules/bluebird/js/main/async.js:15:14)

Node version: 4.4.5
Request version: 2.72.0

**Comment by esvinson** [comment]
Most likely you are using a login that doesn't have proper access.
You're probably getting a response similar to this after login:
```
<RETS ReplyCode="0" ReplyText="Success">
<RETS-RESPONSE>
MemberName=[removed]
User=[removed]
Broker=RETS_OFFIC
MetadataVersion=01.01.79089
MetadataTimestamp=2016-07-18T22:07:06Z
MinMetadataTimestamp=2016-07-18T22:07:06Z
Login=/acc/rets/login
Logout=/acc/rets/logout
X-Selector=/acc/rets/logselector
</RETS-RESPONSE>
</RETS>
```

This doesn't have the normal GetMetadata, GetObject, and Search endpoints.  Only Login, Logout, and whatever X-Selector is.

http://stackoverflow.com/a/11240432/385824

A bit of error handling should probably be added to client.login to handle logins to a feed that don't have all the url_key entries populated.

Example of a working session:
```
<RETS ReplyCode="0" ReplyText="Login Request" >
<RETS-RESPONSE>
MemberName=[removed]
User=[removed]
Broker=951,951
MetadataVersion=16.7.27062
MetadataTimestamp=2016-07-18T19:02:33Z
MinMetadataTimestamp=2016-07-18T19:02:33Z
TimeoutSeconds=6000
GetMetadata=/rets/[removed]/getmetadata
GetObject=/rets/[removed]/getobject
Login=http://[removed]/rets/[removed]/login
Logout=/rets/[removed]/logout
Search=/rets/[removed]/search
</RETS-RESPONSE>
</RETS>
```

**Comment by esvinson** [comment]
As a followup to this, we were getting the missing endpoint issue when connecting with a non-whitelisted IP address.  Switching to a proxy that had the whitelisted IP fixed the issue.
