### ISSUE TITLE
getAllObjects promise never resolves.

### ISSUE THREAD

**Issue by ranleung** [sbruno81/rets-client#41]
Hi, just wanted to ask if anyone else is having this problem.  Whenever I call get `getAllObjects`, `getObjects`, or `getPreferredObjects`, I do not get a promise returned.  No resolve or reject is invoked in my callback.  Note that I am able to login properly.

Here is my code:
```
rets.getAutoLogoutClient(clientSettings, function (client) {
    return client.objects.getAllObjects("Property", "LargePhoto", photoSourceId, {alwaysGroupObjects: true, ObjectData: '*'})
  }).then(function(photoResults) {
    console.log(photoResults)
  }).catch(function(errorInfo) {
    console.log(errorInfo)
  })
```

**Comment by zacronos** [comment]
I'll look into this soon.  Hopefully it is just a small bug.
