### ISSUE TITLE
RETS-SessionID is invalid after a couple of requests

### ISSUE THREAD

**Issue by RonCan** [sbruno81/rets-client#52]
I'm trying to replicate data from RETS server but as soon as I make around 2/3 queries I get the following:
`error: {"err":{"retsMethod":"search","httpStatus":401,"httpStatusMessage":"RETS-Session-ID is invalid.","name":"RetsServerError","message":"RETS Server error while attempting search - HTTP Status 401 returned (RETS-Session-ID is invalid.)","headerInfo":{"server":"Microsoft-IIS/6.0","xAspNetVersion":"2.0.50727","wwwAuthenticate":"Digest realm=\"CCRM\", nonce=\"ae290988b3d6b34199577268da0be23a\", opaque=\"4347ccfffdc73ec464772caf28b5831d\", qop=\"auth\"","vary":"Accept-Encoding","cacheControl":"private","contentType":"text/xml","date":"Sat, 30 Jul 2016 00:05:52 GMT","retsVersion":"RETS/1.7.2","connection":"close","xPoweredBy":"ASP.NET (L002)"}},"resourceName":"Agent","className":"MEMB","query":"(LastModifiedDateTime=1970-01-01T00:00:00+)","limit":300,"offset":601}`

It doesn't make sense. Happens every time I run the request second or third time. Am I doing something wrong?

**Comment by zacronos** [comment]
It's hard to say from just that information.  I would suggest trying to create a very simple example that replicates the problem, and then post that code -- someone might be able to see if there is an issue in your code.

An example issue would be if you are not using promises correctly, and there is a race condition where your client gets logged out while you are still making queries -- that could possibly lead to something like you describe.

**Comment by RonCan** [comment]
It was happening because another instance of the client using the same credentials was running as a cron job and some RETS servers do not allow more than one connection at a time and the latest session is kept and all the others log out, my bad. Closing this now
