### ISSUE TITLE
XML parsing error: not well-formed (invalid token)

### ISSUE THREAD

**Issue by ameerh** [sbruno81/rets-client#54]
Hi,

Thanks for the great library.

I'm getting 'XML parsing error: not well-formed (invalid token)' for some calls. Mostly it's when I increase limit or put no limit. Like in this case limit 50 works but limit 100 or more doesn't. 

```
var clientSettings = {
  loginUrl: retsLoginUrl,
  username: retsUsername,
  password: retsPassword,
  version: 'RETS/1.7.2',
  userAgent: 'RETS node-client/4.x',
  method: 'GET'
};

rets.getAutoLogoutClient(clientSettings, function (client) {

  return client.search.query("PROPERTY", "RES", "(ListingStatus=|1), (LastModDt=2016-07-01T00:00:00-2016-07-20T00:00:00)", {limit: 100})
    .then(function (data) {

      console.log(data.results.length)
      console.log(data.count)
    });

}).catch(function (errorInfo) {
  var error = errorInfo.error || errorInfo;
  console.log("ERROR: issue encountered here: "+(error.stack||error));
});
```

The same call directly works fine
```

var request = require("request").defaults({jar: true});
var loginURL = "http://";
var queryURL = "http://Search.ashx?SearchType=Property&Class=RES&QueryType=DMQL2&Query=(ListingStatus=|1),(LastModDt=2016-07-01T00:00:00-2016-07-20T00:00:00)&Format=COMPACT-DECODED&StandardNames=0&Limit=100";


request.get(loginURL, {
  'auth': {
    'user': 'xxx',
    'pass': 'xxx',
    'sendImmediately': false
  },
  headers: {
    'User-Agent': 'request'
  }
}, function(err, response, body){
  if(err) {
    console.log(err);
  }
  else{
    request.get(queryURL, {
      'auth': {
        'user': 'xxx',
        'pass': 'xxx',
        'sendImmediately': false
      },
      headers: {
        'User-Agent': 'request'
      }
    }, function(err, res , body){
      if(err) {
        console.log(err);
      }
      else{
        console.log(res)
        console.log(body)
      }
    });
  }
});

```

**Comment by ranleung** [comment]
+1.  Getting the same error.  Comes up randomly.  
For example, when I limit to 2000, sometimes i will get the error at 1302.  But when I run the same query again, it runs properly. 

Note that I am also using Rets version: RETS/1.7.2.

**Comment by esvinson** [comment]
Try setting the parserEncoding option to ISO-8859-1.

Based on your parameters I'm guessing it's the feed I had to implement that feature for.

**Comment by ameerh** [comment]
Thanks for the reply.

Here's how I'm setting the 5th parameter:

`
return client.search.query("PROPERTY", "RES", "(ListingStatus=|1), (LastModDt=2016-08-16T00:00:00-2016-08-17T00:00:00)", {limit: 100}, {parserEncoding: 'ISO-8859-1'})
`

And

`
return client.search.query("PROPERTY", "RES", "(ListingStatus=|1), (LastModDt=2016-08-16T00:00:00-2016-08-17T00:00:00)", {limit: 100, parserEncoding: 'ISO-8859-1'})
`

But the error remains.

**Comment by esvinson** [comment]
Was going to mention that the last param should be a string.  Glad it's working for you now!
