### ISSUE TITLE
Debugging 

### ISSUE THREAD

**Issue by jwdotjs** [sbruno81/rets-client#56]
```
You will need to ensure dev dependencies (in particular, request-debug) are installed for rets-client. The easiest way to do this is to first change directory to the location of rets-client (e.g. cd ./node_modules/rets-client), and then run npm install
```

I am of the opinion that if an option is available in the module that it should be available both in production and during development. For instance, our team may want to dump out logs from rets-client in prod and look at production logs to track a particular error. This could be possible with flipping an ENV var, but since there is a dev-dependency that would fail and the restart would crash since request-debug isn't installed on the prod server.

I think since this is made available to the developers via options, `request-debug` should not be considered a dev-dependency. It adds a bit of extra overhead on the npm install, but it doesn't cause fatal breaks if a developer tries using it in an environment when he can't npm install inside node_modules.

If our team created a pull request to move this from dev-dependencies to dependencies, would it get merged?

Either way, thanks for building this library. It's a lifesaver!

**Comment by jwdotjs** [comment]
Also as a side note, this came up because our project had request-debug as a dependency but it wasn't utilized anywhere in our repo so it seemed safe to remove. Then once that was merged, things suddenly break because a required dependency of an installed module doesn't exist.

**Comment by zacronos** [comment]
Fair enough, I think I was concerned about performance, but since I already have to to ensure `request-debug` isn't used unless an appropriate option is turned on, this probably isn't an issue.  Yes, a PR like you described would be merged.
