### ISSUE TITLE
Examples fail on live 1.7 RETS Server

### ISSUE THREAD

**Issue by thebabelfish** [sbruno81/rets-client#6]
I copied and pasted the example code from branch 2.2 (the version with promises...sweet!).

Here is what I had just for clarity:

##The code I ran
//create rets-client

var retsLoginUrl =     'http://######.connectmls.com/rets/server/login'; //changed for this post
var retsPassword = '####; //changed for this post
var retsUser = '#####'; ///changed for this post

var clientSettings = {
    loginUrl:retsLoginUrl,
    username:retsUser,
    password:retsPassword,
    version:'RETS/1.7.2',
    userAgent:'RETS node-client/1.0'
};

var rets = require('rets-promise');
var outputFields = function(obj, fields) {
    for (var i=0; i<fields.length; i++) {
        console.log(fields[i]+": "+obj[fields[i]]);
    }
    console.log("");
};
// establish connection to RETS server which auto-logs out when we're done
rets.getAutoLogoutClient(clientSettings, function (client) {
    //get resources metadata
    return client.metadata.getResources()
        .then(function (data) {
            console.log("======================================");
            console.log("========  Resources Metadata  ========");
            console.log("======================================");
            outputFields(data, ['Version', 'Date']);
            for (var dataItem = 0; dataItem < data.Resources.length; dataItem++) {
                console.log("-------- Resource " + dataItem + " --------");
                outputFields(data.Resources[dataItem], ['ResourceID', 'StandardName', 'VisibleName', 'ObjectVersion']);
            }
        }).then(function () {
            //get class metadata
            return client.metadata.getClass("Property");
        }).then(function (data) {
            console.log("===========================================================");
            console.log("========  Class Metadata (from Property Resource)  ========");
            console.log("===========================================================");
            outputFields(data, ['Version', 'Date', 'Resource']);
            for (var classItem = 0; classItem < data.Classes.length; classItem++) {
                console.log("-------- Table " + classItem + " --------");
                outputFields(data.Classes[classItem], ['ClassName', 'StandardName', 'VisibleName', 'TableVersion']);
            }
        }).then(function () {
            //get field data for open houses
            return client.metadata.getTable("Property", "RE");
        }).then(function (data) {
            console.log("=============================================");
            console.log("========  OpenHouse Table Metadata  ========");
            console.log("=============================================");
            outputFields(data, ['Version', 'Date', 'Resource', 'Class']);
            for (var tableItem = 0; tableItem < data.Fields.length; tableItem++) {
                console.log("-------- Field " + tableItem + " --------");
                outputFields(data.Fields[tableItem], ['MetadataEntryID', 'SystemName', 'ShortName', 'LongName', 'DataType']);
            }
            return data.Fields
        }).then(function (fieldsData) {
            var plucked = [];
            for (var fieldItem = 0; fieldItem < fieldsData.length; fieldItem++) {
                plucked.push(fieldsData[fieldItem].SystemName);
            }
            return plucked;
        }).then(function (fields) {
            //perform a query using DQML2 -- pass resource, class, and query, and options
            return client.search.queryWithOpts("OpenHouse", "RE", "(L_PictureCount=1+)", {limit:100, offset:1})
                .then(function (results) {
                    console.log("===========================================");
                    console.log("========  OpenHouse Query Results  ========");
                    console.log("===========================================");
                    console.log("");
                    //iterate through search results
                    for (var dataItem = 0; dataItem < results.length; dataItem++) {
                        console.log("-------- Result " + dataItem + " --------");
                        outputFields(results[dataItem], fields);
                    }
                });
        }).then(function () {
            // get photos
            return client.objects.getPhotos("Property", "Photo", photoId)
        }).then(function (photoList) {
            console.log("=================================");
            console.log("========  Photo Results  ========");
            console.log("=================================");
            for (var i = 0; i < photoList.length; i++) {
                console.log("Photo " + (i + 1) + " MIME type: " + photoList[i].mime);
                fs.writeFileSync(
                    "./tmp/photo" + (i + 1) + "." + photoList[i].mime.match(/\w+\/(\w+)/i)[1],
                    photoList[i].buffer
                );
            }
        });
}).catch(function (error) {
    console.log("ERROR: issue encountered: "+(error.stack||error));
});

## The console output

/usr/local/bin/node rets2-promise-test.js
ERROR: issue encountered: TypeError: undefined is not a function
  at Object.logout (/Users/orion/node_modules/rets-client/lib/auth.js:78:5)
  at /Users/orion/node_modules/rets-client/lib/client.coffee:103:12
  at tryCatcher (/Users/orion/node_modules/bluebird/js/main/util.js:24:31)
  at Function.Promise.fromNode (/Users/orion/node_modules/bluebird/js/main/promise.js:148:30)
  at Client.logout (/Users/orion/node_modules/rets-client/lib/client.coffee:102:13)
  at /Users/orion/node_modules/rets-client/index.js:26:21
  at Object.finallyHandler (/Users/orion/node_modules/bluebird/js/main/finally.js:40:23)
  at Object.tryCatcher (/Users/orion/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._settlePromiseFromHandler (/Users/orion/node_modules/bluebird/js/main/promise.js:454:31)
  at Promise._settlePromiseAt (/Users/orion/node_modules/bluebird/js/main/promise.js:530:18)
  at Promise._settlePromises (/Users/orion/node_modules/bluebird/js/main/promise.js:646:14)
  at Async._drainQueue (/Users/orion/node_modules/bluebird/js/main/async.js:177:16)
  at Async._drainQueues (/Users/orion/node_modules/bluebird/js/main/async.js:187:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/orion/node_modules/bluebird/js/main/async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
Process finished with exit code 0

For your reference (I'm sure you know the code and can find it, but thought this would make it easier to pinpoint)
The line where the retsSession var is undefined.

![screen shot 2015-06-05 at 9 58 00 pm](https://cloud.githubusercontent.com/assets/2791611/8018024/1e37108e-0bce-11e5-9c7a-c25f28cf3c83.png)

Am I doing something wrong?  Any ideas on how to fix/address the issue.

**Comment by zacronos** [comment]
Hey @thebabelfish, sorry I missed this issue.  I've made some updates and bugfixes to this branch since you opened the issue, and I've also fixed a few bugs in the example in the README.  If you try now, using the new example code, do you still hit an error?

**Comment by zacronos** [comment]
Closing for now on the assumption it is fixed.
