### ISSUE TITLE
client.objects.stream.getObject doesn't reject the promise when fails

### ISSUE THREAD

**Issue by RonCan** [sbruno81/rets-client#62]
I'm getting a`Error while processing RETS response for getObject - XML parsing error: syntax error` in the fail function of `object.stream.js` but it doesn't reject the promise and hence, without notifying the client, the program closes. Please fix

**Comment by zacronos** [comment]
@RonCan:

I'm not sure what you mean; the `fail` function does reject the promise: https://github.com/sbruno81/rets-client/blob/master/lib/clientModules/object.stream.coffee#L152

Please note what version of `rets-client` you are using, and include a sample of code that leads to the error.

**Comment by RonCan** [comment]
I was using `4.1.0` version of rets-client. Using the latest version solved it for me
