### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by svenvarkel** [sbruno81/rets-client#66]
Hi!

First thanks for effort to create client software for such a complex system!

I can connect and authenticate to CARETS (California RETS) but I get an error when I try to search for listings:

`            return client.search.query("Property", "RES", "(ListPrice=100000%2B)")`

would give

`{ RetsReplyError: RETS Server reply while attempting search - ReplyCode 20203 (MISC_SEARCH_ERROR); ReplyText: Illegal RestrictedIndicator character, values are a..z, A..Z, 0..9`

Any idea what's the problem?

**Comment by esvinson** [comment]
Add a 4th parameter as:
```
{ restrictedIndicator: 'RESTRICTED' }
```

It defaults to *** which isn't acceptable by some RETS servers.

**Comment by svenvarkel** [comment]
Thanks, it helped!
