### ISSUE TITLE
Timestamps in photo objects

### ISSUE THREAD

**Issue by howardengelhart** [sbruno81/rets-client#72]
Hi.. when using .objects.stream.getObjects to retrieve images for a listing I see timestamps coming back with strings ```"modifiedDate":"1/3/2017 11:03:56 AM"```.  Is that how it comes from the source?  Looking to see how to handle timezone.  Thanks.

**Comment by zacronos** [comment]
Hi @howardengelhart,

There is no custom handling of timestamp metadata for photo objects, so what you are seeing must be the way it comes from the source.

Depending on the RETS version of the server you are working with, there may be a timezone offset specified in the results of the `.metadata.getSystem()` call.  If there's not, I believe the RETS specs specify that you should assume UTC (though you should double-check me on that for the specific RETS version of the server you're connecting to).

**Comment by howardengelhart** [comment]
```
  timeZoneOffset: undefined,
```
bummer.  I'll take it up with the vendor.  Thanks for the quick reply @zacronos !
