### ISSUE TITLE
Queries fail often with  statusCodes 401 at authentication or 400 at search

### ISSUE THREAD

**Issue by svenvarkel** [sbruno81/rets-client#73]
I'm trying to connect to CARETS (California MLS) and sometimes the client works, sometimes not. It randomly fails with exactly the same parameters, authentication etc.

Has anyone noticed that?

The query is very simple:
```
 rets-client:main RETS search (streaming) { QueryType: 'DMQL2',
  Format: 'COMPACT-DECODED',
  Count: 1,
  StandardNames: 0,
  RestrictedIndicator: 'RESTRICTED',
  Limit: 10,
  Offset: 1,
  SearchType: 'Property',
  Class: 'RES',
  Query: '(ModificationTimestamp=2017-02-01T00:00:00-2017-02-20T00:00:00)' }
```

Debug info:

```
rets-client:request request: { debugId: 1,
  uri: 'CARETS_URL_HERE...',
  method: 'POST',
  headers:
   { 'User-Agent': 'CARETS-General/1.0',
     'RETS-Version': 'RETS/1.8',
     host: 'CARETS_HOST_HERE...',
     'content-type': 'application/x-www-form-urlencoded' } } +27ms
  rets-client:request auth: { debugId: 1,
  statusCode: 401,
  headers:
   { server: 'nginx',
     date: 'Tue, 28 Feb 2017 14:16:20 GMT',
     'content-type': 'text/html',
     'content-length': '0',
     connection: 'close',
     'x-copyright': 'Copyright 2017 Metropolitan Regional Information Systems, Inc., unauthorized use is prohibited.',
     'cache-control': 'private',
     'rets-version': 'RETS/1.8',
     'www-authenticate': 'Digest realm="DIGEST_REALM_HERE...", nonce="3134383832393133383030373820a6f94e5d98a7ad45eb17d3be3b90c538", opaque="6e6f742075236564"' },
  uri: 'CARETS_URL_HERE...' } +368ms
```

**Comment by esvinson** [comment]
We don't have any issues with CARETS.

I'm not seeing an error in your debug info, a 401 auth challenge between requests is expected behavior.

**Comment by zacronos** [comment]
@svenvarkel are you trying to run multiple queries simultaneously with the same credentials?  Some RETS servers limit or completely forbid that, and one of the ways they communicate that is with a 401 Unauthorized response.

Different servers can have very different behaviors regarding simultaneous logins, unfortunately.  Some prohibit the new login that would go past the limit, others invalidate an earlier session.  I've also seen various errors used to communicate this, including an HTTP 401, but also including various RETS error codes.  If you suspect this might be the problem, you should reach out to your support contact with CARETS to see if they can verify the cause of the errors you are receiving.

**Comment by svenvarkel** [comment]
Thanks for quick replies!

I add some more logs here, now with the 400 error, too. I'm not trying to connect too many times etc. I have a simple test script, that uses rets-client to authenticate and make this one search and it fails randomly. I'll try to contact CARETS support to see if they can help.

Nevermind the difference in query params in this search - it acts the same weird way. Sometimes it works, sometimes it doesn't.

Logs:

 ```
rets-client:request request: { debugId: 3,
  uri: 'CARETS_URL_HERE.../cornerstone/search',
  method: 'POST',
  headers:
   { 'User-Agent': 'CARETS-General/1.0',
     'RETS-Version': 'RETS/1.8',
     cookie: 'RETS-Session-ID=120166284998',
     'content-type': 'application/x-www-form-urlencoded',
     'content-length': 279,
     authorization: 'Digest username="USERNAME", realm="****", nonce="3134383833363939313533363120cdafa88a61352c583dbbfd43a8545b6f", uri="/cornerstone/search", response="6d98b9e3287002c28665d4c3e173acc9", opaque="6e6f742075736564"',
     referer: 'CARETS_URL_HERE.../cornerstone/search',
     host: 'CARETS_HOST_HERE...' },
  body: 'QueryType=DMQL2&Format=COMPACT-DECODED&Count=1&StandardNames=0&RestrictedIndicator=RESTRICTED&Limit=10&Offset=1&SearchType=Property&Class=RES&Query=%28CARETSListingStatus%3D%7C50041200437%2C50041200438%29%2C%28StatusChangeDate%3D2017-02-01T00%3A00%3A00-2017-02-02T00%3A00%3A00%29' } +2ms
  rets-client:request response: { debugId: 3,
  headers:
   { server: 'nginx',
     date: 'Wed, 01 Mar 2017 12:05:15 GMT',
     'content-type': 'text/plain;charset=ISO-8859-1',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'x-copyright': 'Copyright 2017 Metropolitan Regional Information Systems, Inc., unauthorized use is prohibited.',
     'cache-control': 'private',
     'rets-version': 'RETS/1.8' },
  statusCode: 400 } +350ms
rets-client:main RETS search (streaming) error: RETS Server error while attempting search - HTTP Status 400 returned (Bad Request) +1ms
Error streaming RETS results: RetsServerError: RETS Server error while attempting search - HTTP Status 400 returned (Bad Request)
{ RetsServerError: RETS Server error while attempting search - HTTP Status 400 returned (Bad Request)
    at Request.responseHandler (/sandbox/retsclient/node_modules/rets-client/dist/utils/retsHttp.js:70:17)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:189:7)
    at Request.onRequestResponse (/sandbox/retsclient/node_modules/request/request.js:986:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:189:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  httpStatus: 400,
  httpStatusMessage: 'Bad Request',
  name: 'RetsServerError',
  retsMethod: 'search',
  queryOptions:
   { QueryType: 'DMQL2',
     Format: 'COMPACT-DECODED',
     Count: 1,
     StandardNames: 0,
     RestrictedIndicator: 'RESTRICTED',
     Limit: 10,
     Offset: 1,
     SearchType: 'Property',
     Class: 'RES',
     Query: '(CARETSListingStatus=|50041200437,50041200438),(StatusChangeDate=2017-02-01T00:00:00-2017-02-02T00:00:00)' },
  headerInfo:
   { server: 'nginx',
     date: 'Wed, 01 Mar 2017 12:05:15 GMT',
     contentType: 'text/plain;charset=ISO-8859-1',
     transferEncoding: 'chunked',
     connection: 'close',
     xCopyright: 'Copyright 2017 Metropolitan Regional Information Systems, Inc., unauthorized use is prohibited.',
     cacheControl: 'private',
     retsVersion: 'RETS/1.8' },
  message: 'RETS Server error while attempting search - HTTP Status 400 returned (Bad Request)' }
```

**Comment by zacronos** [comment]
Thanks for posting the additional error.

Hmm.  Off the top of my head, I don't see anything wrong.  (That doesn't mean there isn't though, I could very easily be missing something.)

If you can get in touch with CARETS support, I'd be very curious to hear what they say the problem is.

**Comment by esvinson** [comment]
Try specifying your RETS version as 1.7.2.  We're using 1.7.2 with CARETS and it appears you're using 1.8.

**Comment by svenvarkel** [comment]
Thanks for tip, @esvinson! I tried with it earlier with similar results, then changed to 1.8 and if I remember correctly it worked also for some requests. Anyway, now all my requests are failing. I'll continue investigating it. Soon I'll go as deep as using wireshark and intercepting raw network requests:)

**Comment by svenvarkel** [comment]
I did some more testing and I'm facing exactly the same behaviour with PMAR (Portland MLS), too. Some requests work, some fail. I'm still trying to figure out the pattern.

**Comment by svenvarkel** [comment]
I now got a tiny bit of information - the  'set-cookie':
      [ 'JSESSIONID=CE25F0B0CCE8562A72C3311F98FF8C5D; Path=/; HttpOnly',
        'JSESSIONID=CE25F0B0CCE8562A72C3311F98FF8C5D; Path=/' ],

header DIFFERS in those cases where request fails for subsequent requests (auth, search). The JSESSIONID is the same for successful requests.

**Comment by svenvarkel** [comment]
After debugging and thinking a lot about the flow I finally understood that the problem was in my implementation. I'm used to simpler promises flow than in that client. I resolved  a promise or two too early and this caused the autoLogoutClient to log out. In order to overcome that I initialize the standard client and log out manually after pulling everything I need.

Thanks to all of you for trying to help out!
