### ISSUE TITLE
Question.. Is it possible to specify more than one Property Class in a single search?

### ISSUE THREAD

**Issue by howardengelhart** [sbruno81/rets-client#74]
For instance.. Resi,Condo,Coop?  I looked through the code and it doesn't seem like much is done with the class param.. so was wondering if there was a value that could be used to search across all classes..

**Comment by esvinson** [comment]
The RETS spec does not support that.  You'd need to do a separate query on each class and then combine the results in your code.

http://www.rapattoni.com/rets-172-specification/file
Section 7.3.1

**Comment by howardengelhart** [comment]
That’s what I thought, thanks!
