### ISSUE TITLE
Photo Streaming for multiple listing ID's returns Invalid Identifier.

### ISSUE THREAD

**Issue by GifCo** [sbruno81/rets-client#78]
Hi guys,

I am unable to get more than a single listings photos at a time when using objects.stream. I can pass in a single listing ID and get all photos for that listing no problem. However when I pass in an array or an object with multiple listing ID's I get Invalid Identifier.

Could you let me know if the client.objects.stream.getObjects() is handling the request for multiple listings or is this done at the RETS server level and my specific RETS just does not support this?

From what I can see rets-client just seems to be concatenating my array of ID's into one long comma separated string which my RETS will not accept.

Thanks.

**Comment by zacronos** [comment]
It should be handled at the RETS server level, as you noted the `rets-client` code just concatenates them and lets the server handle it all at once.  Of course it is possible there is something happening incorrectly with the concatenation.

Can you turn on debugging (https://github.com/sbruno81/rets-client#debugging) and post the ID string that is being used?  Also, can you let us know which RETS version your server is using?

**Comment by esvinson** [comment]
From what I can tell in the RETS 1.7.2 spec it should allow you to specify an ID string with comma separated values of something like: `LISTINGID1:*,LISTINGID2:*`  I haven't tested to see if the rets-client is generating that value properly when specifying multiple Listing IDs, as we currently only do photo syncing for individual listings.  As zacronos mentioned a debug output would be helpful to see if there might be a bug in how that's being generated.

**Comment by GifCo** [comment]
Hey thanks for the reply's!

So I'm on RETS 1.7.2

Using client.objects.stream.getObjects() and passing in an array:
let photos = ['18045583', '16592327', '16947720']

The ID being passed to the RETS is "ID": "18045583,16592327,16947720"

passing in an object: 
let photoIds = { '18045583': '*',   '16592327': '*',     '16947720': '*'   };

RETS ID =  "ID": "16592327:*,16947720:*,18045583:*"

Passing in a single ID as a string everything works as expected, same for passing in an array with a single ID.

Bellow is the full debug console log when I try an array of strings (first example).

   ERROR: issue encountered:
      replyCode: "20402"
      replyText: "Invalid Identifier"
      name: "RetsReplyError"
      replyTag: "INVALID_IDENTIFIER"
      retsMethod: "getObject"
      queryOptions: {
        "Location": 0,
        "ObjectData": "*",
        "Type": "LargePhoto",
        "Resource": "Property",
        "ID": "18045583,16592327,16947720"
      }
      headerInfo: {
        "cacheControl": "private",
        "contentLength": "196",
        "contentType": "text/xml",
        "server": "Microsoft-IIS/8.0",
        "retsVersion": "RETS/1.7.2",
        "retsRequestId": "",
        "xAspNetVersion": "4.0.30319",
        "xPoweredBy": "ASP.NET",
        "date": "Fri, 05 May 2017 17:10:29 GMT",
        "connection": "close"
      }
      message: "RETS Server reply while attempting getObject - ReplyCode 20402 (INVALID_IDENTIFIER); ReplyText: Invalid Identifier"

   RetsReplyError: RETS Server reply while attempting getObject - ReplyCode 20402 (INVALID_IDENTIFIER); ReplyText: Invalid Identifier
       at .<anonymous> (F:\Web_Dev\rets_store\node_modules\rets-client\dist\utils\retsParsing.js:55:28)
       at emitTwo (events.js:111:20)
       at emit (events.js:191:7)
       at Parser.parse (F:\Web_Dev\rets_store\node_modules\node-expat\lib\node-expat.js:23:22)
       at Parser.write (F:\Web_Dev\rets_store\node_modules\node-expat\lib\node-expat.js:60:19)
       at DestroyableTransform.ondata (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_readable.js:546:20)
       at emitOne (events.js:96:13)
       at DestroyableTransform.emit (events.js:188:7)
       at readableAddChunk (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_readable.js:217:18)
       at DestroyableTransform.Readable.push (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_readable.js:176:10)
       at DestroyableTransform.Transform.push (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_transform.js:123:32)
       at afterTransform (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_transform.js:79:51)
       at TransformState.afterTransform (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_transform.js:58:12)
       at DestroyableTransform.noop [as _transform] (F:\Web_Dev\rets_store\node_modules\through2\through2.js:26:3)
       at DestroyableTransform.Transform._read (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_transform.js:159:10)
       at DestroyableTransform.Transform._write (F:\Web_Dev\rets_store\node_modules\readable-stream\lib\_stream_transform.js:147:83)

**Comment by esvinson** [comment]
Try using `getAllObjects` instead of `getObjects` when passing an array.

**Comment by GifCo** [comment]
Didnt even see that! But unfortunately still gives me the same error:

 ERROR: issue encountered:
      replyCode: "20402"
      replyText: "Invalid Identifier"
      name: "RetsReplyError"
      replyTag: "INVALID_IDENTIFIER"
      retsMethod: "getObject"
      queryOptions: {
        "Location": 0,
        "ObjectData": "*",
        "Type": "LargePhoto",
        "Resource": "Property",
        "ID": "18045583:*,16592327:*,16947720:*"
      }
      headerInfo: {
        "cacheControl": "private",
        "contentLength": "196",
        "contentType": "text/xml",
        "server": "Microsoft-IIS/8.0",
        "retsVersion": "RETS/1.7.2",
        "retsRequestId": "",
        "xAspNetVersion": "4.0.30319",
        "xPoweredBy": "ASP.NET",
        "date": "Fri, 05 May 2017 17:49:09 GMT",
        "connection": "close"
      }

**Comment by esvinson** [comment]
I just tested and it appeared to work when using getAllObjects
Example:
```
return client.objects.getAllObjects('Property', 'Photo', ['502880', '503056', '504941'], {alwaysGroupObjects: true, ObjectData: '*', Location: 1})
```
POST parameters generated:
`Location=1&ObjectData=%2A&Type=Photo&Resource=Property&ID=502880%3A%2A%2C503056%3A%2A%2C504941%3A%2A`
URL Decoded: `ID=502880:*,503056:*,504941:*`

That returned the results I was expecting.

**Comment by GifCo** [comment]
@esvinson yea I'm starting to think this is not supported with my RETS.  When passing in exactly what you have I still get Invalid Identifier even though rets-client is passing in the ID's correctly

**Comment by jbendercode** [comment]
Also having issues with what has been mentioned above. Did you have any luck contacting CREA support staff?

**Comment by GifCo** [comment]
@jbendercode yes I just got a reply a few hours ago. CREA DDF does not allow getObject calls with multiple ID's. Only a single Listing ID at a time unfortunately.

There suggesting for initializing a new DB and downloading all photos for all listing is to simply pull the master list and start downloading listing by listing one at a time.

Hope this helps. Closing the issue now.
