### ISSUE TITLE
Client.headers['RETS-UA-Authorization'] after Client.login()

### ISSUE THREAD

**Issue by tjiasan** [sbruno81/rets-client#86]
```
//version 1 (works with hackish fix)
let Client;
Client = new rets.Client(clientSettings);
Client.login()
    .then(()=>{
           //hackish fix
            var a1, retsUaAuth;
            if (Client.settings.userAgentPassword && Client.settings.sessionId) {
                a1 = crypto.createHash('md5').update([Client.settings.userAgent, 
             Client.settings.userAgentPassword].join(":")).digest('hex');
                retsUaAuth = crypto.createHash('md5').update([a1, "", Client.settings.sessionId || "", 
          Client.settings.version || Client.headers['RETS-Version']].join(":")).digest('hex');
                Client.headers['RETS-UA-Authorization'] = "Digest " + retsUaAuth;
            }
            return Client.search.query(resource, class_name, query, search_options)
        })
    .then(res =>{
        Client.logout()
    })

//version 2  (works fine):
rets.getAutoLogoutClient(clientSettings, function (client) {
    return client.search.query(resource, class_name,query, search_options)
        .then(function (searchData) {
        console.log(client.search.client.settings)
            console.log(searchData)
        });
    }).catch(function (errorInfo) {
        var error = errorInfo.error || errorInfo;
        console.log("   ERROR: issue encountered:");
        console.log('   '+(error.stack||error).replace(/\n/g, '\n   '));
});

```

I'm having an issue with SFAR where the RETS-UA-Authorization header is lost during subsequent queries after login, giving an unauthorized client password error. Whereas the second version of the code works fine and retains the header throughout secondary queries.

**Comment by tjiasan** [comment]
`//version 1
let Client;
Client = new rets.Client(clientSettings);
Client.login()
    .then(()=>{
           //hackish fix
            var a1, retsUaAuth;
            if (Client.settings.userAgentPassword && Client.settings.sessionId) {
                a1 = crypto.createHash('md5').update([Client.settings.userAgent, 
             Client.settings.userAgentPassword].join(":")).digest('hex');
                retsUaAuth = crypto.createHash('md5').update([a1, "", Client.settings.sessionId || "", 
          Client.settings.version || Client.headers['RETS-Version']].join(":")).digest('hex');
                Client.headers['RETS-UA-Authorization'] = "Digest " + retsUaAuth;
            }
            return Client.search.query(resource, class_name, query, search_options)
        })
    .then(res =>{
        Client.logout()
    })

//version 2 :
rets.getAutoLogoutClient(clientSettings, function (client) {
    return client.search.query(resource, class_name,query, search_options)
        .then(function (searchData) {
        console.log(client.search.client.settings)
            console.log(searchData)
        });
    }).catch(function (errorInfo) {
        var error = errorInfo.error || errorInfo;
        console.log("   ERROR: issue encountered:");
        console.log('   '+(error.stack||error).replace(/\n/g, '\n   '));
});`

**Comment by esvinson** [comment]
The 'hackish' fix is necessary because the session id doesn't get set until after you login (The getAutoLogoutClient function handles that), so the RETS-UA-Authorization header has to be updated with that session ID after login.  It might be possible to incorporate that logic into an additional `.then` in the login function itself, which is probably a better way to do it than the way I implemented it, but that would have to be tested.

**Comment by esvinson** [comment]
I will take a look at it and do some testing later today.

**Comment by zacronos** [comment]
Good catch, this was a very straightforward change.  It's up on master, but I'm having some trouble with `npm publish` so I haven't cut version 5.0.3 yet.  I'll do that when I can figure out what the problem is.

**Comment by zacronos** [comment]
It's possible the problem is on NPM's end (https://status.npmjs.org/), I'll try again later.

**Comment by zacronos** [comment]
v5.0.3 is up now, it should fix this.

**Comment by tjiasan** [comment]
Thanks a lot, really helpful
