### ISSUE TITLE
error getting photos

### ISSUE THREAD

**Issue by crivera** [sbruno81/rets-client#93]
Hi 

i am trying to follow the code and test the getting of photos but i am not sure if have a wrong id or something else

i am using the standard code

`rets.getAutoLogoutClient(clientSettings, function (client) {
  return client.objects.getAllObjects('Property', 'LargePhoto', '184415436', {alwaysGroupObjects: true, ObjectData: '*'})
}).then(function (photoResults) {
  console.log('=================================')
  console.log('========  Photo Results  ========')
  console.log('=================================')
  console.log('   ~~~~~~~~~ Header Info ~~~~~~~~~')
  outputFields(photoResults.headerInfo)
  for (var i = 0; i < photoResults.objects.length; i++) {
    console.log('   -------- Photo ' + (i + 1) + ' --------')
    if (photoResults.objects[i].error) {
      console.log('      Error: ' + photoResults.objects[i].error)
    } else {
      outputFields(photoResults.objects[i].headerInfo)
    }
  }
}).catch(function (errorInfo) {
  var error = errorInfo.error || errorInfo
  console.log('   ERROR: issue encountered:')
  outputFields(error)
  console.log('   ' + (error.stack || error).replace(/\n/g, '\n   '))
})`

but get the following error:

`ERROR: issue encountered:
      replyCode: "20401"
      replyText: "Invalid Type"
      name: "RetsReplyError"
      replyTag: "INVALID_OBJECT_TYPE"
      retsMethod: "getObject"
      queryOptions: {
        "Location": 0,
        "ObjectData": "*",
        "Type": "LargePhoto",
        "Resource": "Property",
        "ID": "184415436:*"
      }
      headerInfo: {
        "server": "Apache-Coyote/1.1",
        "setCookie": "JSESSIONID=BEFB1148196BEAD6D0C5DDEAE50EB4CF; Path=/contact",
        "mimeVersion": "1.0",
        "cacheControl": "private",
        "retsVersion": "RETS/1.8",
        "contentType": "text/xml",
        "contentLength": "53",
        "date": "Wed, 15 Nov 2017 20:28:49 GMT",
        "connection": "close"
      }
      message: "RETS Server reply while attempting getObject - ReplyCode 20401 (INVALID_OBJECT_TYPE); ReplyText: Invalid Type"
`

i am using the id from the property 

"ListingId":"OC17206923",
"ListingKeyNumeric":"184415436",

but neither work

do i need to use another field?

Sorry first time working with RETS

Thanks
Chris

**Comment by crivera** [comment]
not an issue... found out my rets server does not allow getObject and i need to query for photos

**Comment by settugowtham** [comment]
Hey Chris,

Could you please provide sample code for reference? I'm facing the same issue 

Thanks
Gowthan
