### ISSUE TITLE
client.search.query throwing "Error while processing RETS response for search - Failed to parse delimiter"

### ISSUE THREAD

**Issue by anchoritnext** [sbruno81/rets-client#97]
QueryOptions = { QueryType: 'DMQL2',
     Format: 'COMPACT-DECODED',
     Count: 1,
     StandardNames: 0,
     RestrictedIndicator: '***',
     Limit: 1,
     SearchType: 'Listing',
     Class: 'Listing',
     Query: '(SaleOrRental=S)' }

Problem seems to stem from getStreamParser function in retsParsing.js where delimiter is being set to null because of no metadataTag. Any ideas?

**Comment by esvinson** [comment]
The RETS spec specifies `A tab character (an octet with a value of 09) is the default delimiter unless another is specified as part of the transaction.` so I think I'd consider it a bug that it defaults to null.  https://github.com/sbruno81/rets-client/blob/master/lib/utils/retsParsing.coffee#L69
Updating that to '\t' should work, as it should be overridden if it sees a delimiter tag.

**Comment by anchoritnext** [comment]
Great. Thanks. I can change that locally for now. Any chance it can be fixed in the next release?
